// Database types - will be auto-generated by Supabase CLI
// For now, we define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      households: {
        Row: {
          id: string;
          name: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          household_id: string | null;
          display_name: string | null;
          avatar_url: string | null;
          role: "owner" | "member";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          household_id?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          role?: "owner" | "member";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string | null;
          display_name?: string | null;
          avatar_url?: string | null;
          role?: "owner" | "member";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      ingredients: {
        Row: {
          id: string;
          name: string;
          normalized_name: string;
          category: string | null;
          default_unit: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          normalized_name: string;
          category?: string | null;
          default_unit?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          normalized_name?: string;
          category?: string | null;
          default_unit?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      recipes: {
        Row: {
          id: string;
          household_id: string;
          created_by: string | null;
          title: string;
          description: string | null;
          image_url: string | null;
          prep_time_minutes: number | null;
          cook_time_minutes: number | null;
          servings: number;
          cuisine: string | null;
          meal_type: string[];
          tags: string[];
          source_type: "manual" | "url_import" | "ocr" | "ai_generated" | null;
          source_url: string | null;
          is_favorite: boolean;
          times_cooked: number;
          last_cooked_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          created_by?: string | null;
          title: string;
          description?: string | null;
          image_url?: string | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number;
          cuisine?: string | null;
          meal_type?: string[];
          tags?: string[];
          source_type?: "manual" | "url_import" | "ocr" | "ai_generated" | null;
          source_url?: string | null;
          is_favorite?: boolean;
          times_cooked?: number;
          last_cooked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          created_by?: string | null;
          title?: string;
          description?: string | null;
          image_url?: string | null;
          prep_time_minutes?: number | null;
          cook_time_minutes?: number | null;
          servings?: number;
          cuisine?: string | null;
          meal_type?: string[];
          tags?: string[];
          source_type?: "manual" | "url_import" | "ocr" | "ai_generated" | null;
          source_url?: string | null;
          is_favorite?: boolean;
          times_cooked?: number;
          last_cooked_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipes_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipes_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      recipe_ingredients: {
        Row: {
          id: string;
          recipe_id: string;
          ingredient_id: string;
          quantity: number | null;
          unit: string | null;
          preparation: string | null;
          notes: string | null;
          is_optional: boolean;
          display_order: number;
          original_text: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          ingredient_id: string;
          quantity?: number | null;
          unit?: string | null;
          preparation?: string | null;
          notes?: string | null;
          is_optional?: boolean;
          display_order?: number;
          original_text?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          ingredient_id?: string;
          quantity?: number | null;
          unit?: string | null;
          preparation?: string | null;
          notes?: string | null;
          is_optional?: boolean;
          display_order?: number;
          original_text?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_ingredients_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipe_ingredients_ingredient_id_fkey";
            columns: ["ingredient_id"];
            isOneToOne: false;
            referencedRelation: "ingredients";
            referencedColumns: ["id"];
          },
        ];
      };
      recipe_steps: {
        Row: {
          id: string;
          recipe_id: string;
          step_number: number;
          instruction: string;
          duration_minutes: number | null;
          image_url: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          recipe_id: string;
          step_number: number;
          instruction: string;
          duration_minutes?: number | null;
          image_url?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          recipe_id?: string;
          step_number?: number;
          instruction?: string;
          duration_minutes?: number | null;
          image_url?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_steps_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      meal_plans: {
        Row: {
          id: string;
          household_id: string;
          week_start: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          week_start: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          week_start?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "meal_plans_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
        ];
      };
      meal_entries: {
        Row: {
          id: string;
          meal_plan_id: string;
          recipe_id: string | null;
          date: string;
          meal_type: "breakfast" | "lunch" | "dinner" | "snack";
          custom_meal_name: string | null;
          servings_multiplier: number;
          is_completed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meal_plan_id: string;
          recipe_id?: string | null;
          date: string;
          meal_type: "breakfast" | "lunch" | "dinner" | "snack";
          custom_meal_name?: string | null;
          servings_multiplier?: number;
          is_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meal_plan_id?: string;
          recipe_id?: string | null;
          date?: string;
          meal_type?: "breakfast" | "lunch" | "dinner" | "snack";
          custom_meal_name?: string | null;
          servings_multiplier?: number;
          is_completed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "meal_entries_meal_plan_id_fkey";
            columns: ["meal_plan_id"];
            isOneToOne: false;
            referencedRelation: "meal_plans";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "meal_entries_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      shopping_lists: {
        Row: {
          id: string;
          household_id: string;
          meal_plan_id: string | null;
          name: string;
          status: "active" | "completed" | "archived";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          meal_plan_id?: string | null;
          name?: string;
          status?: "active" | "completed" | "archived";
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          meal_plan_id?: string | null;
          name?: string;
          status?: "active" | "completed" | "archived";
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "shopping_lists_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "shopping_lists_meal_plan_id_fkey";
            columns: ["meal_plan_id"];
            isOneToOne: false;
            referencedRelation: "meal_plans";
            referencedColumns: ["id"];
          },
        ];
      };
      shopping_list_items: {
        Row: {
          id: string;
          shopping_list_id: string;
          ingredient_id: string | null;
          name: string;
          quantity: number | null;
          unit: string | null;
          category: string | null;
          aisle: string | null;
          is_checked: boolean;
          checked_at: string | null;
          checked_by: string | null;
          is_manual: boolean;
          source_recipe_ids: string[];
          adjusted_quantity: number | null;
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shopping_list_id: string;
          ingredient_id?: string | null;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          category?: string | null;
          aisle?: string | null;
          is_checked?: boolean;
          checked_at?: string | null;
          checked_by?: string | null;
          is_manual?: boolean;
          source_recipe_ids?: string[];
          adjusted_quantity?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shopping_list_id?: string;
          ingredient_id?: string | null;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          category?: string | null;
          aisle?: string | null;
          is_checked?: boolean;
          checked_at?: string | null;
          checked_by?: string | null;
          is_manual?: boolean;
          source_recipe_ids?: string[];
          adjusted_quantity?: number | null;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "shopping_list_items_shopping_list_id_fkey";
            columns: ["shopping_list_id"];
            isOneToOne: false;
            referencedRelation: "shopping_lists";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "shopping_list_items_ingredient_id_fkey";
            columns: ["ingredient_id"];
            isOneToOne: false;
            referencedRelation: "ingredients";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "shopping_list_items_checked_by_fkey";
            columns: ["checked_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      inventory_items: {
        Row: {
          id: string;
          household_id: string;
          ingredient_id: string | null;
          name: string;
          quantity: number | null;
          unit: string | null;
          location: "fridge" | "freezer" | "pantry";
          expiry_date: string | null;
          source: "manual" | "ai_scan" | "shopping_list" | null;
          confidence_score: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          ingredient_id?: string | null;
          name: string;
          quantity?: number | null;
          unit?: string | null;
          location?: "fridge" | "freezer" | "pantry";
          expiry_date?: string | null;
          source?: "manual" | "ai_scan" | "shopping_list" | null;
          confidence_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          ingredient_id?: string | null;
          name?: string;
          quantity?: number | null;
          unit?: string | null;
          location?: "fridge" | "freezer" | "pantry";
          expiry_date?: string | null;
          source?: "manual" | "ai_scan" | "shopping_list" | null;
          confidence_score?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "inventory_items_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "inventory_items_ingredient_id_fkey";
            columns: ["ingredient_id"];
            isOneToOne: false;
            referencedRelation: "ingredients";
            referencedColumns: ["id"];
          },
        ];
      };
      fridge_scans: {
        Row: {
          id: string;
          household_id: string;
          scanned_by: string | null;
          image_url: string;
          scan_type: "fridge" | "freezer" | "pantry" | "receipt";
          raw_ai_response: Json | null;
          items_detected: number | null;
          status: "pending" | "processing" | "completed" | "failed";
          error_message: string | null;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          household_id: string;
          scanned_by?: string | null;
          image_url: string;
          scan_type?: "fridge" | "freezer" | "pantry" | "receipt";
          raw_ai_response?: Json | null;
          items_detected?: number | null;
          status?: "pending" | "processing" | "completed" | "failed";
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          household_id?: string;
          scanned_by?: string | null;
          image_url?: string;
          scan_type?: "fridge" | "freezer" | "pantry" | "receipt";
          raw_ai_response?: Json | null;
          items_detected?: number | null;
          status?: "pending" | "processing" | "completed" | "failed";
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "fridge_scans_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "fridge_scans_scanned_by_fkey";
            columns: ["scanned_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      recipe_imports: {
        Row: {
          id: string;
          household_id: string;
          imported_by: string | null;
          import_type: "url" | "ocr" | "photo";
          source_url: string | null;
          image_url: string | null;
          recipe_id: string | null;
          status: "pending" | "processing" | "completed" | "failed" | "review_needed";
          raw_ai_response: Json | null;
          confidence_score: number | null;
          error_message: string | null;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          household_id: string;
          imported_by?: string | null;
          import_type: "url" | "ocr" | "photo";
          source_url?: string | null;
          image_url?: string | null;
          recipe_id?: string | null;
          status?: "pending" | "processing" | "completed" | "failed" | "review_needed";
          raw_ai_response?: Json | null;
          confidence_score?: number | null;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          household_id?: string;
          imported_by?: string | null;
          import_type?: "url" | "ocr" | "photo";
          source_url?: string | null;
          image_url?: string | null;
          recipe_id?: string | null;
          status?: "pending" | "processing" | "completed" | "failed" | "review_needed";
          raw_ai_response?: Json | null;
          confidence_score?: number | null;
          error_message?: string | null;
          created_at?: string;
          processed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "recipe_imports_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipe_imports_imported_by_fkey";
            columns: ["imported_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "recipe_imports_recipe_id_fkey";
            columns: ["recipe_id"];
            isOneToOne: false;
            referencedRelation: "recipes";
            referencedColumns: ["id"];
          },
        ];
      };
      household_invitations: {
        Row: {
          id: string;
          household_id: string;
          email: string;
          invited_by: string;
          status: "pending" | "accepted" | "declined" | "expired";
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          household_id: string;
          email: string;
          invited_by: string;
          status?: "pending" | "accepted" | "declined" | "expired";
          expires_at?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          household_id?: string;
          email?: string;
          invited_by?: string;
          status?: "pending" | "accepted" | "declined" | "expired";
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "household_invitations_household_id_fkey";
            columns: ["household_id"];
            isOneToOne: false;
            referencedRelation: "households";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "household_invitations_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      get_user_household_id: {
        Args: Record<string, never>;
        Returns: string;
      };
      generate_shopping_list: {
        Args: { p_meal_plan_id: string; p_deduct_inventory?: boolean };
        Returns: string;
      };
      is_email_household_member: {
        Args: { p_household_id: string; p_email: string };
        Returns: boolean;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

// Helper types
export type Tables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Row"];
export type InsertTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Insert"];
export type UpdateTables<T extends keyof Database["public"]["Tables"]> =
  Database["public"]["Tables"][T]["Update"];
